### ISSUE TITLE
Hello Ilaki

### ISSUE THREAD

**Issue by essekia** [ilaki/dynamic-form#1]
Sorry about this,

Just wanted to contact you and to know if you are looking for a UI development role in Trichy. Sorry about using issues to contact you.

**Comment by ilaki** [comment]
No probs. Just curious how you got to my account though😂. Also I am currently not looking for job. But thank you for connecting.

**Comment by ilaki** [comment]
No probs. Just curious how you got to my account though😂. Also I am currently not looking for job. But thank you for connecting.
